### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by Athanasius** [pprovart/CGThresholds#1]
Hi,  I'm the new maintainer for EDMC itself.  I intend to move releases over to Python 3.7 sometime in the next 1-2 weeks.  As such your users who upgrade EDMC will see your plugin stop working at that point.

I'm first looking at adding some code to the upcoming final Python 2.7-based release of EDMC to detect plugins that don't yet have a `plugin_start3()` method and alert the user.  So your users will start getting that alert when I release (what is planned to be) 3.4.6.0 / 3.46.

If you check [EDMC Available Plugins](https://github.com/EDCD/EDMarketConnector/wiki/Plugins#available-plugins) I can tell you that at least 'Habitable Zone' has already updated, so you could use it as a reference.  Several others have as well, including dual Python 2.7/3.7 support.

**Comment by blueeagle69** [comment]
Please update this plugin 😣

**Comment by Athanasius** [comment]
And given how much later this is... just get it working on Python 3.9, don't bother with dual 2.7/3.x support, as users really should be using EDMC 4.x or later now.

**Comment by SayakMukhopadhyay** [comment]
@blueeagle69 I am not sure how popular this plugin is but if you are ok with an alternative, you can checkout https://inara.cz/galaxy-communitygoals/

**Comment by blueeagle69** [comment]
Cheers. 
I do use Inara.
